In [2]:
import numpy as np
import pandas as pd 

## Animaux

In [3]:
anim = pd.read_csv("/Users/fannydgo/Documents/Data analyst/P3_Di Giusto_Fanny/FAO_2013_fr/fr_animaux.csv") 
anim.head(20)

Code Domaine                                            Domaine  Code zone  \
0          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
1          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
2          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
3          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
4          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
5          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
6          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
7          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
8          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
9          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
10         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
11         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
12         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
13         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
14         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
15         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
16         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
17         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
18         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
19         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

           Zone  Code Élément  \
0   Afghanistan          5511   
1   Afghanistan          5611   
2   Afghanistan          5301   
3   Afghanistan          5142   
4   Afghanistan           645   
5   Afghanistan           664   
6   Afghanistan           674   
7   Afghanistan           684   
8   Afghanistan          5511   
9   Afghanistan          5301   
10  Afghanistan          5142   
11  Afghanistan           645   
12  Afghanistan           664   
13  Afghanistan           674   
14  Afghanistan           684   
15  Afghanistan          5511   
16  Afghanistan          5611   
17  Afghanistan          5301   
18  Afghanistan          5142   
19  Afghanistan           645   

                                              Élément  Code Produit  \
0                                          Production          2731   
1                             Importations - Quantité          2731   
2                            Disponibilité intérieure          2731   
3                                          Nourriture          2731   
4   Disponibilité alimentaire en quantité (kg/pers...          2731   
5      Disponibilité alimentaire (Kcal/personne/jour)          2731   
6   Disponibilité de protéines en quantité (g/pers...          2731   
7   Disponibilité de matière grasse en quantité (g...          2731   
8                                          Production          2732   
9                            Disponibilité intérieure          2732   
10                                         Nourriture          2732   
11  Disponibilité alimentaire en quantité (kg/pers...          2732   
12     Disponibilité alimentaire (Kcal/personne/jour)          2732   
13  Disponibilité de protéines en quantité (g/pers...          2732   
14  Disponibilité de matière grasse en quantité (g...          2732   
15                                         Production          2734   
16                            Importations - Quantité          2734   
17                           Disponibilité intérieure          2734   
18                                         Nourriture          2734   
19  Disponibilité alimentaire en quantité (kg/pers...          2734   

                   Produit  Code année  Année               Unité  Valeur  \
0         Viande de Bovins        2013

## Céréales

In [4]:
céré = pd.read_csv("/Users/fannydgo/Documents/Data analyst/P3_Di Giusto_Fanny/FAO_2013_fr/fr_céréales.csv")
céré

Code Domaine                                            Domaine  \
0           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
1           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
2           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
3           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
4           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
..           ...                                                ...   
886         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
887         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
888         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
889         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
890         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   

     Code zone         Zone  Code Élément     Élément  Code Produit  \
0            2  Afghanistan          5511  Production          2511   
1            2  Afghanistan          5511  Production          2805   
2            2  Afghanistan          5511  Production          2513   
3            2  Afghanistan          5511  Production          2514   
4            2  Afghanistan          5511  Production          2517   
..         ...          ...           ...         ...           ...   
886        181     Zimbabwe          5511  Production          2514   
887        181     Zimbabwe          5511  Production          2516   
888        181     Zimbabwe          5511  Production          2517   
889        181     Zimbabwe          5511  Production          2518   
890        181     Zimbabwe          5511  Production          2520   

              Produit  Code année  Année               Unité  Valeur Symbole  \
0                 Blé        2013   2013  Milliers de tonnes    5169       S   
1    Riz (Eq Blanchi)        2013   2013  Milliers de tonnes     342       S   
2                Orge        2013   2013  Milliers de tonnes     514       S   
3                Maïs        2013   2013  Milliers de tonnes     312       S   
4              Millet        2013   2013  Milliers de tonnes      13       S   
..                ...         ...    ...                 ...     ...     ...   
886              Maïs        2013   2013  Milliers de tonnes     799       S   
887            Avoine        2013   2013  Milliers de tonnes       1       S   
888            Millet        2013   2013  Milliers de tonnes      55       S   
889            Sorgho        2013   2013  Milliers de tonnes      69       S   
890  Céréales, Autres        2013   2013  Milliers de tonnes       2       S   

    Description du Symbole  
0    Données standardisées  
1    Données standardisées  
2    Données standardisées  
3    Données standardisées  
4    Données standardisées  
..                     ...  
886  Données standardisées  
887  Données standardisées  
888  Données standardisées  
889  Données standardisées  
890  Données standardisées  

[891 rows x 14 columns]

## Population 

In [5]:
pop = pd.read_csv("/Users/fannydgo/Documents/Data analyst/P3_Di Giusto_Fanny/FAO_2013_fr/fr_population.csv")
pop

Code Domaine                                            Domaine  \
0           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
1           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
2           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
3           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
4           FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
..           ...                                                ...   
170         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
171         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
172         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
173         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
174         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   

     Code zone                                    Zone  Code Élément  \
0            2                             Afghanistan           511   
1          202                          Afrique du Sud           511   
2            3                                 Albanie           511   
3            4                                 Algérie           511   
4           79                               Allemagne           511   
..         ...                                     ...           ...   
170        236  Venezuela (République bolivarienne du)           511   
171        237                                Viet Nam           511   
172        249                                   Yémen           511   
173        251                                  Zambie           511   
174        181                                Zimbabwe           511   

               Élément  Code Produit     Produit  Code année  Année  \
0    Population totale          2501  Population        2013   2013   
1    Population totale          2501  Population        2013   2013   
2    Population totale          2501  Population        2013   2013   
3    Population totale          2501  Population        2013   2013   
4    Population totale          2501  Population        2013   2013   
..                 ...           ...         ...         ...    ...   
170  Population totale          2501  Population        2013   2013   
171  Population totale          2501  Population        2013   2013   
172  Population totale          2501  Population        2013   2013   
173  Population totale          2501  Population        2013   2013   
174  Population totale          2501  Population        2013   2013   

              Unité  Valeur Symbole Description du Symbole  
0    1000 personnes   30552     NaN      Donnée officielle  
1    1000 personnes   52776     NaN      Donnée officielle  
2    1000 personnes    3173     NaN      Donnée officielle  
3    1000 personnes   39208     NaN      Donnée officielle  
4    1000 personnes   82727     NaN      Donnée officielle  
..              ...     ...     ...                    ...  
170  1000 personnes   30405     NaN      Donnée officielle  
171  1000 personnes   91680     NaN      Donnée officielle  
172  1000 personnes   24407     NaN      Donnée officielle  
173  1000 personnes   14539     NaN      Donnée officielle  
174  1000 personnes   14150     NaN      Donnée officielle  

[175 rows x 14 columns]

In [6]:
pop.describe(include='all')

Code Domaine                                            Domaine  \
count           175                                                175   
unique            1                                                  1   
top            FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
freq            175                                                175   
mean            NaN                                                NaN   
std             NaN                                                NaN   
min             NaN                                                NaN   
25%             NaN                                                NaN   
50%             NaN                                                NaN   
75%             NaN                                                NaN   
max             NaN                                                NaN   

         Code zone     Zone  Code Élément            Élément  Code Produit  \
count   175.000000      175         175.0                175         175.0   
unique         NaN      175           NaN                  1           NaN   
top            NaN  Bahamas           NaN  Population totale           NaN   
freq           NaN        1           NaN                175           NaN   
mean    126.720000      NaN         511.0                NaN        2501.0   
std      75.168519      NaN           0.0                NaN           0.0   
min       1.000000      NaN         511.0                NaN        2501.0   
25%      64.500000      NaN         511.0                NaN        2501.0   
50%     121.000000      NaN         511.0                NaN        2501.0   
75%     188.500000      NaN         511.0                NaN        2501.0   
max     351.000000      NaN         511.0                NaN        2501.0   

           Produit  Code année   Année           Unité        Valeur Symbole  \
count          175       175.0   175.0             175  1.750000e+02       1   
unique           1         NaN     NaN               1           NaN       1   
top     Population         NaN     NaN  1000 personnes           NaN       A   
freq           175         NaN     NaN             175           NaN       1   
mean           NaN      2013.0  2013.0             NaN  4.807996e+04     NaN   
std            NaN         0.0     0.0             NaN  1.786327e+05     NaN   
min            NaN      2013.0  2013.0             NaN  5.400000e+01     NaN   
25%            NaN      2013.0  2013.0             NaN  2.543500e+03     NaN   
50%            NaN      2013.0  2013.0             NaN  9.413000e+03     NaN   
75%            NaN      2013.0  2013.0             NaN  2.888150e+04     NaN   
max            NaN      2013.0  2013.0             NaN  1.416667e+06     NaN   

       Description du Symbole  
count                     175  
unique                      2  
top         Donnée officielle  
freq                      174  
mean                      NaN  
std                       NaN  
min                       NaN  
25%                       NaN  
50%                       NaN  
75%                       NaN  
max                       NaN

In [7]:
pop_non_officielle = pop [ (pop["Description du Symbole"] != "Donnée officielle")]
pop_non_officielle

Code Domaine                                            Domaine  Code zone  \
33         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        351   

     Zone  Code Élément            Élément  Code Produit     Produit  \
33  Chine           511  Population totale          2501  Population   

    Code année  Année           Unité   Valeur Symbole  \
33        2013   2013  1000 personnes  1416667       A   

                               Description du Symbole  
33  Agrégat, peut inclure des données officielles,...

In [8]:
pop.loc[30:40,:]

Code Domaine                                            Domaine  Code zone  \
30         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         32   
31         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         33   
32         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         40   
33         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        351   
34         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         96   
35         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        128   
36         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         41   
37         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        214   
38         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         50   
39         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         44   
40         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         46   

                         Zone  Code Élément            Élément  Code Produit  \
30                   Cameroun           511  Population totale          2501   
31                     Canada           511  Population totale          2501   
32                      Chili           511  Population totale          2501   
33                      Chine           511  Population totale          2501   
34   Chine - RAS de Hong-Kong           511  Population totale          2501   
35       Chine - RAS de Macao           511  Population totale          2501   
36        Chine, continentale           511  Population totale          2501   
37  Chine, Taiwan Province de           511  Population totale          2501   
38                     Chypre           511  Population totale          2501   
39                   Colombie           511  Population totale          2501   
40                      Congo           511  Population totale          2501   

       Produit  Code année  Année           Unité   Valeur Symbole  \
30  Population        2013   2013  1000 personnes    22254     NaN   
31  Population        2013   2013  1000 personnes    35182     NaN   
32  Population        2013   2013  1000 personnes    17620     NaN   
33  Population        2013   2013  1000 personnes  1416667       A   
34  Population        2013   2013  1000 personnes     7204     NaN   
35  Population        2013   2013  1000 personnes      566     NaN   
36  Population        2013   2013  1000 personnes  1385567     NaN   
37  Population        2013   2013  1000 personnes    23330     NaN   
38  Population        2013   2013  1000 personnes     1141     NaN   
39  Population        2013   2013  1000 personnes    48321     NaN   
40  Population        2013   2013  1000 personnes     4448     NaN   

                               Description du Symbole  
30                                  Donnée officielle  
31                                  Donnée officielle  
32                                  Donnée officielle  
33  Agrégat, peut inclure des données officielles,...  
34                                  Donnée officielle  
35                                  Donnée officielle  
36                                  Donnée officielle  
37                                  Donnée officielle  
38                                  Donnée officielle  
39                                  Donnée officielle  
40                                  Donnée officielle

On peut ici constater que certaines données de la Chine sont redondantes et qu'il faudrait supprimer les code pays 96, 128, 41 et 214 pour que les données soient pertinentes

## Sous alimentation 

In [10]:
alim = pd.read_csv("/Users/fannydgo/Documents/Data analyst/P3_Di Giusto_Fanny/FAO_2013_fr/fr_sousalimentation.csv")
alim.describe(include='all')

Code Domaine                             Domaine    Code zone     Zone  \
count          1020                                1020  1020.000000     1020   
unique            1                                   1          NaN      204   
top              FS  Données de la sécurité alimentaire          NaN  Islande   
freq           1020                                1020          NaN        5   
mean            NaN                                 NaN   129.264706      NaN   
std             NaN                                 NaN    76.615019      NaN   
min             NaN                                 NaN     1.000000      NaN   
25%             NaN                                 NaN    62.500000      NaN   
50%             NaN                                 NaN   127.500000      NaN   
75%             NaN                                 NaN   193.250000      NaN   
max             NaN                                 NaN   351.000000      NaN   

        Code Élément Élément  Code Produit  \
count         1020.0    1020        1020.0   
unique           NaN       1           NaN   
top              NaN  Valeur           NaN   
freq             NaN    1020           NaN   
mean          6132.0     NaN      210011.0   
std              0.0     NaN           0.0   
min           6132.0     NaN      210011.0   
25%           6132.0     NaN      210011.0   
50%           6132.0     NaN      210011.0   
75%           6132.0     NaN      210011.0   
max           6132.0     NaN      210011.0   

                                                  Produit    Code année  \
count                                                1020  1.020000e+03   
unique                                                  1           NaN   
top     Nombre de personnes sous-alimentées (millions)...           NaN   
freq                                                 1020           NaN   
mean                                                  NaN  2.014202e+07   
std                                                   NaN  1.415049e+04   
min                                                   NaN  2.012201e+07   
25%                                                   NaN  2.013202e+07   
50%                                                   NaN  2.014202e+07   
75%                                                   NaN  2.015202e+07   
max                                                   NaN  2.016202e+07   

            Année     Unité Valeur Symbole Description du Symbole  Note  
count        1020      1020    605    1020                   1020   0.0  
unique          5         1    146       3                      3   NaN  
top     2015-2017  millions   <0.1       F         Estimation FAO   NaN  
freq          204      1020    115     605                    605   NaN  
mean          NaN       NaN    NaN     NaN                    NaN   NaN  
std           NaN       NaN    NaN     NaN                    NaN   NaN  
min           NaN       NaN    NaN     NaN                    NaN   NaN  
25%           NaN       NaN    NaN     NaN                    NaN   NaN  
50%           NaN       NaN    NaN     NaN                    NaN   NaN  
75%           NaN       NaN    NaN     NaN                    NaN   NaN  
max           NaN       NaN    NaN     NaN                    NaN   NaN

In [9]:
alim_non_officielle = alim [ (alim["Symbole"] != "F")]
alim_non_officielle = alim_non_officielle [ (alim_non_officielle["Symbole"] != "NR")]
alim_non_officielle

Code Domaine                             Domaine  Code zone     Zone  \
25            FS  Données de la sécurité alimentaire          6  Andorre   
26            FS  Données de la sécurité alimentaire          6  Andorre   
27            FS  Données de la sécurité alimentaire          6  Andorre   
28            FS  Données de la sécurité alimentaire          6  Andorre   
29            FS  Données de la sécurité alimentaire          6  Andorre   
..           ...                                 ...        ...      ...   
975           FS  Données de la sécurité alimentaire        227   Tuvalu   
976           FS  Données de la sécurité alimentaire        227   Tuvalu   
977           FS  Données de la sécurité alimentaire        227   Tuvalu   
978           FS  Données de la sécurité alimentaire        227   Tuvalu   
979           FS  Données de la sécurité alimentaire        227   Tuvalu   

     Code Élément Élément  Code Produit  \
25           6132  Valeur        210011   
26           6132  Valeur        210011   
27           6132  Valeur        210011   
28           6132  Valeur        210011   
29           6132  Valeur        210011   
..            ...     ...           ...   
975          6132  Valeur        210011   
976          6132  Valeur        210011   
977          6132  Valeur        210011   
978          6132  Valeur        210011   
979          6132  Valeur        210011   

                                               Produit  Code année      Année  \
25   Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014   
26   Nombre de personnes sous-alimentées (millions)...    20132015  2013-2015   
27   Nombre de personnes sous-alimentées (millions)...    20142016  2014-2016   
28   Nombre de personnes sous-alimentées (millions)...    20152017  2015-2017   
29   Nombre de personnes sous-alimentées (millions)...    20162018  2016-2018   
..                                                 ...         ...        ...   
975  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014   
976  Nombre de personnes sous-alimentées (millions)...    20132015  2013-2015   
977  Nombre de personnes sous-alimentées (millions)...    20142016  2014-2016   
978  Nombre de personnes sous-alimentées (millions)...    20152017  2015-2017   
979  Nombre de personnes sous-alimentées (millions)...    20162018  2016-2018   

        Unité Valeur Symbole Description du Symbole  Note  
25   millions    NaN      NV         Non disponible   NaN  
26   millions    NaN      NV         Non disponible   NaN  
27   millions    NaN      NV         Non disponible   NaN  
28   millions    NaN      NV         Non disponible   NaN  
29   millions    NaN      NV         Non disponible   NaN  
..        ...    ...     ...                    ...   ...  
975  millions    NaN      NV         Non disponible   NaN  
976  millions    NaN      NV         Non disponible   NaN  
977  millions    NaN      NV         Non disponible   NaN  
978  millions    NaN      NV         Non disponible   NaN  
979  millions    NaN      NV         Non disponible   NaN  

[185 rows x 15 columns]

## Végétaux

In [10]:
végé = pd.read_csv("/Users/fannydgo/Documents/Data analyst/P3_Di Giusto_Fanny/FAO_2013_fr/fr_vegetaux.csv")
végé.head(20)

Code Domaine                                            Domaine  Code zone  \
0          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
1          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
2          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
3          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
4          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
5          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
6          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
7          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
8          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
9          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
10         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
11         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
12         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
13         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
14         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
15         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
16         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
17         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
18         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
19         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

           Zone  Code Élément  \
0   Afghanistan          5511   
1   Afghanistan          5611   
2   Afghanistan          5072   
3   Afghanistan          5301   
4   Afghanistan          5527   
5   Afghanistan          5123   
6   Afghanistan          5142   
7   Afghanistan           645   
8   Afghanistan           664   
9   Afghanistan           674   
10  Afghanistan           684   
11  Afghanistan          5511   
12  Afghanistan          5611   
13  Afghanistan          5301   
14  Afghanistan          5527   
15  Afghanistan          5123   
16  Afghanistan          5142   
17  Afghanistan           645   
18  Afghanistan           664   
19  Afghanistan           674   

                                              Élément  Code Produit  \
0                                          Production          2511   
1                             Importations - Quantité          2511   
2                                  Variation de stock          2511   
3                            Disponibilité intérieure          2511   
4                                            Semences          2511   
5                                              Pertes          2511   
6                                          Nourriture          2511   
7   Disponibilité alimentaire en quantité (kg/pers...          2511   
8      Disponibilité alimentaire (Kcal/personne/jour)          2511   
9   Disponibilité de protéines en quantité (g/pers...          2511   
10  Disponibilité de matière grasse en quantité (g...          2511   
11                                         Production          2805   
12                            Importations - Quantité          2805   
13                           Disponibilité intérieure          2805   
14                                           Semences          2805   
15                                             Pertes          2805   
16                                         Nourriture          2805   
17  Disponibilité alimentaire en quantité (kg/pers...          2805   
18     Disponibilité alimentaire (Kcal/personne/jour)          2805   
19  Disponibilité de protéines en quantité (g/pers...          2805   

             Produit  Code année  Année               Unité   Valeur Symbole  \
0                Blé        2013   

# Trie et nettoyage des données

## Population, Végétaux et animaux 

Test clef "Code zone" : Dataframe population 

In [11]:
popClef = pop.drop_duplicates(['Code zone'])
len(pop) == len(popClef)

True

In [12]:
pop = pop.loc[~pop["Code zone"].isin([96, 128, 41, 214])]
pop.rename(columns={'Valeur': 'Population'}, inplace=True)
pop = pop.loc[:,['Code zone','Zone','Population']]
pop['Population'] *= 1000
pop

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Code zone                                    Zone  Population
0            2                             Afghanistan    30552000
1          202                          Afrique du Sud    52776000
2            3                                 Albanie     3173000
3            4                                 Algérie    39208000
4           79                               Allemagne    82727000
..         ...                                     ...         ...
170        236  Venezuela (République bolivarienne du)    30405000
171        237                                Viet Nam    91680000
172        249                                   Yémen    24407000
173        251                                  Zambie    14539000
174        181                                Zimbabwe    14150000

[171 rows x 3 columns]

Test clefs "Code zone + Code Élément + Code Produit" : Dataframes Animaux et Végétaux 

In [13]:
animClef = anim.drop_duplicates(['Code zone','Code Élément','Code Produit'])
len(anim) == len(animClef)

True

In [14]:
végéClef = végé.drop_duplicates(['Code zone','Code Élément','Code Produit'])
len(végé) == len(végéClef)

True

In [15]:
végé['Origine'] = 'Végétaux'
anim['Origine'] = 'Animaux'
animVégé = pd.concat([anim, végé])
animVégé = animVégé.loc[~animVégé["Code zone"].isin([96, 128, 41, 214])]
animVégé = animVégé.pivot_table(index=['Zone','Produit','Code Produit','Origine'], columns=['Élément'], values='Valeur')
animVégé = animVégé.reset_index()
animVégé = animVégé.fillna(0)
animVégé = pd.merge(pop, animVégé, on='Zone', how='right')
animVégé

Code zone         Zone  Population                Produit  \
0              2  Afghanistan    30552000       Abats Comestible   
1              2  Afghanistan    30552000        Agrumes, Autres   
2              2  Afghanistan    30552000  Aliments pour enfants   
3              2  Afghanistan    30552000                 Ananas   
4              2  Afghanistan    30552000                Bananes   
...          ...          ...         ...                    ...   
15320        181     Zimbabwe    14150000       Viande de Suides   
15321        181     Zimbabwe    14150000    Viande de Volailles   
15322        181     Zimbabwe    14150000          Viande, Autre   
15323        181     Zimbabwe    14150000                    Vin   
15324        181     Zimbabwe    14150000         Épices, Autres   

       Code Produit   Origine  Aliments pour animaux  \
0              2736   Animaux                    0.0   
1              2614  Végétaux                    0.0   
2              2680  Végétaux                    0.0   
3              2618  Végétaux                    0.0   
4              2615  Végétaux                    0.0   
...             ...       ...                    ...   
15320          2733   Animaux                    0.0   
15321          2734   Animaux                    0.0   
15322          2735   Animaux                    0.0   
15323          2655  Végétaux                    0.0   
15324          2645  Végétaux                    0.0   

       Autres utilisations (non alimentaire)  \
0                                        0.0   
1                                        0.0   
2                                        0.0   
3                                        0.0   
4                                        0.0   
...                                      ...   
15320                                    0.0   
15321                                    0.0   
15322                                    1.0   
15323                                    0.0   
15324                                    0.0   

       Disponibilité alimentaire (Kcal/personne/jour)  \
0                                                 5.0   
1                                                 1.0   
2                                                 1.0   
3                                                 0.0   
4                                                 4.0   
...                                               ...   
15320                                            24.0   
15321                                            17.0   
15322                                             7.0   
15323                                             1.0   
15324                                             1.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  ...  \
0                                                   1.72       ...   
1                                                   1.29       ...   
2                                                   0.06       ...   
3                                                   0.00       ...   
4                                                   2.70       ...   
...                                                  ...       ...   
15320                                               2.65       ...   
15321                                               4.97       ...   
15322                                               2.29       ...   
15323                                               0.27       ...   
15324                                               0.06       ...   

       Disponibilité de protéines en quantité (g/personne/jour)  \
0                                                   0.77          
1                                                   0.02          
2                                                   0.03          
3                                                   0.00          
4                                                   0.05          
...         

## Céréales en 2013

Test clefs "Code zone + Code Produit" : Dataframe céréales

In [16]:
céréClef = céré.drop_duplicates(['Code zone','Code Produit'])
len(céréClef) == len(céré)

True

In [17]:
céré = céré.loc[~céré["Code zone"].isin([96, 128, 41, 214])]
céré = céré[['Code zone', "Élément",'Code Produit', "Produit", "Unité", "Valeur"]]
céré = pd.merge(céré, pop, on='Code zone', how='left')
céré

Code zone     Élément  Code Produit           Produit  \
0            2  Production          2511               Blé   
1            2  Production          2805  Riz (Eq Blanchi)   
2            2  Production          2513              Orge   
3            2  Production          2514              Maïs   
4            2  Production          2517            Millet   
..         ...         ...           ...               ...   
869        181  Production          2514              Maïs   
870        181  Production          2516            Avoine   
871        181  Production          2517            Millet   
872        181  Production          2518            Sorgho   
873        181  Production          2520  Céréales, Autres   

                  Unité  Valeur         Zone  Population  
0    Milliers de tonnes    5169  Afghanistan    30552000  
1    Milliers de tonnes     342  Afghanistan    30552000  
2    Milliers de tonnes     514  Afghanistan    30552000  
3    Milliers de tonnes     312  Afghanistan    30552000  
4    Milliers de tonnes      13  Afghanistan    30552000  
..                  ...     ...          ...         ...  
869  Milliers de tonnes     799     Zimbabwe    14150000  
870  Milliers de tonnes       1     Zimbabwe    14150000  
871  Milliers de tonnes      55     Zimbabwe    14150000  
872  Milliers de tonnes      69     Zimbabwe    14150000  
873  Milliers de tonnes       2     Zimbabwe    14150000  

[874 rows x 8 columns]

## Sous alimentation et population en 2013

In [18]:
alim = alim.drop_duplicates(['Code zone','Année'])
alim = alim.loc[~alim["Code zone"].isin([96, 128, 41, 214])]
alim = alim[['Code zone', "Produit",'Code Produit', "Année", "Unité", "Valeur", "Description du Symbole", "Symbole"]]
alim = alim [ (alim["Symbole"] == "F")]
alim2013 = alim [ (alim["Année"] == "2012-2014")]
alim2013 = pd.merge(pop, alim2013, how='left', on="Code zone")
alim2013


Code zone                                    Zone  Population  \
0            2                             Afghanistan    30552000   
1          202                          Afrique du Sud    52776000   
2            3                                 Albanie     3173000   
3            4                                 Algérie    39208000   
4           79                               Allemagne    82727000   
..         ...                                     ...         ...   
166        236  Venezuela (République bolivarienne du)    30405000   
167        237                                Viet Nam    91680000   
168        249                                   Yémen    24407000   
169        251                                  Zambie    14539000   
170        181                                Zimbabwe    14150000   

                                               Produit  Code Produit  \
0    Nombre de personnes sous-alimentées (millions)...      210011.0   
1    Nombre de personnes sous-alimentées (millions)...      210011.0   
2    Nombre de personnes sous-alimentées (millions)...      210011.0   
3    Nombre de personnes sous-alimentées (millions)...      210011.0   
4                                                  NaN           NaN   
..                                                 ...           ...   
166  Nombre de personnes sous-alimentées (millions)...      210011.0   
167  Nombre de personnes sous-alimentées (millions)...      210011.0   
168  Nombre de personnes sous-alimentées (millions)...      210011.0   
169  Nombre de personnes sous-alimentées (millions)...      210011.0   
170  Nombre de personnes sous-alimentées (millions)...      210011.0   

         Année     Unité Valeur Description du Symbole Symbole  
0    2012-2014  millions    7.9         Estimation FAO       F  
1    2012-2014  millions    2.6         Estimation FAO       F  
2    2012-2014  millions    0.2         Estimation FAO       F  
3    2012-2014  millions    1.7         Estimation FAO       F  
4          NaN       NaN    NaN                    NaN     NaN  
..         ...       ...    ...                    ...     ...  
166  2012-2014  millions    1.9         Estimation FAO       F  
167  2012-2014  millions   10.4         Estimation FAO       F  
168  2012-2014  millions    7.2         Estimation FAO       F  
169  2012-2014  millions      7         Estimation FAO       F  
170  2012-2014  millions    6.6         Estimation FAO       F  

[171 rows x 10 columns]

# Questions 

## 1) Population totale

In [19]:
popTotale = alim2013 ['Population'].sum()
print(popTotale)

6997326000


## 2) Redondance des éléments : équations 

In [20]:
bléFrance = animVégé [ (animVégé["Produit"] == "Blé") & (animVégé["Zone"] == "France") ]
bléFrance

Code zone    Zone  Population Produit  Code Produit   Origine  \
5133         68  France    64291000     Blé          2511  Végétaux   

      Aliments pour animaux  Autres utilisations (non alimentaire)  \
5133                 7822.0                                 2824.0   

      Disponibilité alimentaire (Kcal/personne/jour)  \
5133                                           811.0   

      Disponibilité alimentaire en quantité (kg/personne/an)  ...  \
5133                                             108.43       ...   

      Disponibilité de protéines en quantité (g/personne/jour)  \
5133                                              25.99          

      Disponibilité intérieure  Exportations - Quantité  \
5133                   20298.0                  21502.0   

      Importations - Quantité  Nourriture  Pertes  Production  Semences  \
5133                   2055.0      6971.0   358.0     38614.0     748.0   

      Traitement  Variation de stock  
5133      1575.0              1131.0  

[1 rows x 21 columns]

### Disponibilité intérieure = Production + importations - exportations + Variations de stock (augmentation ou diminution) 

In [21]:
bléFrance['Production'].sum() + bléFrance['Importations - Quantité'].sum() - bléFrance['Exportations - Quantité'].sum() + bléFrance['Variation de stock'].sum()



20298.0

### Disponibilité intérieure = Traitement + Perte + Nourriture + Semences + Aliments pour animaux + Autres utilisations

In [22]:
bléFrance["Traitement"].sum() + bléFrance["Pertes"].sum() + bléFrance["Nourriture"].sum() + bléFrance["Semences"].sum() + bléFrance["Aliments pour animaux"].sum() + bléFrance["Autres utilisations (non alimentaire)"].sum()


20298.0

### Conclusion : Production + importations - exportations + Variations de stock (augmentation ou diminution) = Traitement + Perte + Nourriture + Semences + Aliments pour animaux + Autres utilisations

## 3) Disponibilité alimentaire en kcal puis en kg de protéines (pour chaque produit et chaque pays)

In [23]:
animVégé["Disponibilité alimentaire (Kcal)"] = animVégé["Population"] * animVégé['Disponibilité alimentaire (Kcal/personne/jour)'] * 365
animVégé['Disponibilité de protéines en quantité (Kg)'] = animVégé["Disponibilité de protéines en quantité (g/personne/jour)"] * animVégé["Population"] * 365 / 1000
animVégé


Code zone         Zone  Population                Produit  \
0              2  Afghanistan    30552000       Abats Comestible   
1              2  Afghanistan    30552000        Agrumes, Autres   
2              2  Afghanistan    30552000  Aliments pour enfants   
3              2  Afghanistan    30552000                 Ananas   
4              2  Afghanistan    30552000                Bananes   
...          ...          ...         ...                    ...   
15320        181     Zimbabwe    14150000       Viande de Suides   
15321        181     Zimbabwe    14150000    Viande de Volailles   
15322        181     Zimbabwe    14150000          Viande, Autre   
15323        181     Zimbabwe    14150000                    Vin   
15324        181     Zimbabwe    14150000         Épices, Autres   

       Code Produit   Origine  Aliments pour animaux  \
0              2736   Animaux                    0.0   
1              2614  Végétaux                    0.0   
2              2680  Végétaux                    0.0   
3              2618  Végétaux                    0.0   
4              2615  Végétaux                    0.0   
...             ...       ...                    ...   
15320          2733   Animaux                    0.0   
15321          2734   Animaux                    0.0   
15322          2735   Animaux                    0.0   
15323          2655  Végétaux                    0.0   
15324          2645  Végétaux                    0.0   

       Autres utilisations (non alimentaire)  \
0                                        0.0   
1                                        0.0   
2                                        0.0   
3                                        0.0   
4                                        0.0   
...                                      ...   
15320                                    0.0   
15321                                    0.0   
15322                                    1.0   
15323                                    0.0   
15324                                    0.0   

       Disponibilité alimentaire (Kcal/personne/jour)  \
0                                                 5.0   
1                                                 1.0   
2                                                 1.0   
3                                                 0.0   
4                                                 4.0   
...                                               ...   
15320                                            24.0   
15321                                            17.0   
15322                                             7.0   
15323                                             1.0   
15324                                             1.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  ...  \
0                                                   1.72       ...   
1                                                   1.29       ...   
2                                                   0.06       ...   
3                                                   0.00       ...   
4                                                   2.70       ...   
...                                                  ...       ...   
15320                                               2.65       ...   
15321                                               4.97       ...   
15322                                               2.29       ...   
15323                                               0.27       ...   
15324                                               0.06       ...   

       Exportations - Quantité  Importations - Quantité  Nourriture  Pertes  \
0                          0.0                      0.0        53.0     0.0   
1                          2.0                     40.0        39.0     2.0   
2                          0.0                      2.0         2.0     0.0   
3                          0.0                      0.0         0.0     0.0   
4                  

## 4) Ratio "énergie/poids" pour chaque produit

In [24]:
animVégé['Disponibilité alimentaire en quantité (kg)'] = animVégé['Nourriture']*1000000
ratioTot = animVégé.groupby('Produit').sum()
ratioTot['Ratio (kcal/kg)'] = ratioTot['Disponibilité alimentaire (Kcal)'] / ratioTot['Disponibilité alimentaire en quantité (kg)']
ratioTot.drop(['Population', 'Code zone', 'Code Produit'], axis = 1, inplace = True)
ratioTot


Aliments pour animaux  \
Produit                                         
Abats Comestible                       1009.0   
Agrumes, Autres                           0.0   
Alcool, non Comestible                    0.0   
Aliments pour enfants                     0.0   
Ananas                                    0.0   
...                                       ...   
Viande de Suides                          0.0   
Viande de Volailles                       0.0   
Viande, Autre                            57.0   
Vin                                       0.0   
Épices, Autres                            0.0   

                        Autres utilisations (non alimentaire)  \
Produit                                                         
Abats Comestible                                        848.0   
Agrumes, Autres                                          25.0   
Alcool, non Comestible                                21768.0   
Aliments pour enfants                                     0.0   
Ananas                                                    3.0   
...                                                       ...   
Viande de Suides                                        283.0   
Viande de Volailles                                    1259.0   
Viande, Autre                                            15.0   
Vin                                                    1588.0   
Épices, Autres                                          185.0   

                        Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                                  
Abats Comestible                                                1375.0   
Agrumes, Autres                                                  126.0   
Alcool, non Comestible                                             0.0   
Aliments pour enfants                                            604.0   
Ananas                                                           640.0   
...                                                                ...   
Viande de Suides                                               14171.0   
Viande de Volailles                                            12565.0   
Viande, Autre                                                   1055.0   
Vin                                                             1992.0   
Épices, Autres                                                   991.0   

                        Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                                          
Abats Comestible                                                   440.37        
Agrumes, Autres                                                    205.58        
Alcool, non Comestible                                               0.00        
Aliments pour enfants                                               60.36        
Ananas                                                             634.04        
...                                                                   ...        
Viande de Suides                                                  2300.32        
Viande de Volailles                                               3454.95        
Viande, Autre                                                      309.59        
Vin                                                               1043.20        
Épices, Autres                                                     104.58        

                        Disponibilité de matière grasse en quantité (g/personne/jour)  \
Produit                                                                                 
Abats Comestible                                                    40.85               
Agrumes, Autres                                                      0.77               
Alcool, non Comestible                                               0.00               
Aliments pour enfants                                            

In [25]:
ratioTot.loc[['Oeufs'],:]

Aliments pour animaux  Autres utilisations (non alimentaire)  \
Produit                                                                 
Oeufs                     73.0                                  862.0   

         Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                   
Oeufs                                            4499.0   

         Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                           
Oeufs                                              1189.31        

         Disponibilité de matière grasse en quantité (g/personne/jour)  \
Produit                                                                  
Oeufs                                                313.4               

         Disponibilité de protéines en quantité (g/personne/jour)  \
Produit                                                             
Oeufs                                                351.6          

         Disponibilité intérieure  Exportations - Quantité  \
Produit                                                      
Oeufs                     73573.0                   2784.0   

         Importations - Quantité  Nourriture  Pertes  Production  Semences  \
Produit                                                                      
Oeufs                     2550.0     64332.0  3419.0     73792.0    4930.0   

         Traitement  Variation de stock  Disponibilité alimentaire (Kcal)  \
Produit                                                                     
Oeufs           0.0                16.0                      9.169544e+13   

         Disponibilité de protéines en quantité (Kg)  \
Produit                                                
Oeufs                                   7.136641e+09   

         Disponibilité alimentaire en quantité (kg)  Ratio (kcal/kg)  
Produit                                                               
Oeufs                                  6.433200e+10       1425.34723

La valeur calorique d'un oeuf est de 147 Kcal pour environ 100g, soit un ratio (Kcal/kg) de :

In [26]:
théorieKcalOeuf = 147 / (0.1)
print(théorieKcalOeuf)

1470.0


La ratio obtenu à la question 4 est de 1425.34 ce qui est comparable au ratio théorique

## Pourcentage de protéines de chaque produit (pour chaque pays)

In [27]:
pourcentageProt = animVégé.copy()
pourcentageProt['Ratio (prot/kg)'] = (pourcentageProt['Disponibilité de protéines en quantité (g/personne/jour)'] / 1000*365) / pourcentageProt['Disponibilité alimentaire en quantité (kg/personne/an)']
pourcentageProt['Protéines (%)'] = pourcentageProt['Ratio (prot/kg)'] * 100
pourcentageProt


Code zone         Zone  Population                Produit  \
0              2  Afghanistan    30552000       Abats Comestible   
1              2  Afghanistan    30552000        Agrumes, Autres   
2              2  Afghanistan    30552000  Aliments pour enfants   
3              2  Afghanistan    30552000                 Ananas   
4              2  Afghanistan    30552000                Bananes   
...          ...          ...         ...                    ...   
15320        181     Zimbabwe    14150000       Viande de Suides   
15321        181     Zimbabwe    14150000    Viande de Volailles   
15322        181     Zimbabwe    14150000          Viande, Autre   
15323        181     Zimbabwe    14150000                    Vin   
15324        181     Zimbabwe    14150000         Épices, Autres   

       Code Produit   Origine  Aliments pour animaux  \
0              2736   Animaux                    0.0   
1              2614  Végétaux                    0.0   
2              2680  Végétaux                    0.0   
3              2618  Végétaux                    0.0   
4              2615  Végétaux                    0.0   
...             ...       ...                    ...   
15320          2733   Animaux                    0.0   
15321          2734   Animaux                    0.0   
15322          2735   Animaux                    0.0   
15323          2655  Végétaux                    0.0   
15324          2645  Végétaux                    0.0   

       Autres utilisations (non alimentaire)  \
0                                        0.0   
1                                        0.0   
2                                        0.0   
3                                        0.0   
4                                        0.0   
...                                      ...   
15320                                    0.0   
15321                                    0.0   
15322                                    1.0   
15323                                    0.0   
15324                                    0.0   

       Disponibilité alimentaire (Kcal/personne/jour)  \
0                                                 5.0   
1                                                 1.0   
2                                                 1.0   
3                                                 0.0   
4                                                 4.0   
...                                               ...   
15320                                            24.0   
15321                                            17.0   
15322                                             7.0   
15323                                             1.0   
15324                                             1.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  ...  Pertes  \
0                                                   1.72       ...     0.0   
1                                                   1.29       ...     2.0   
2                                                   0.06       ...     0.0   
3                                                   0.00       ...     0.0   
4                                                   2.70       ...     0.0   
...                                                  ...       ...     ...   
15320                                               2.65       ...     0.0   
15321                                               4.97       ...     0.0   
15322                                               2.29       ...     0.0   
15323                                               0.27       ...     0.0   
15324                                               0.06       ...     0.0   

       Production  Semences  Traitement  Variation de stock  \
0            53.0       0.0         0.0                 0.0   
1             3.0       0.0         0.0                 0.0   
2             0.0       0.0         0.0                 0.0   
3             0.0       0.0         0.0                 0.0   
4  

## 5) Aliments les plus caloriques

In [28]:
calAlim = animVégé.loc[(~animVégé["Disponibilité alimentaire (Kcal)"].isin(["inf", "NaN",0]))&(~animVégé["Disponibilité alimentaire en quantité (kg)"].isin(["inf", "NaN",0]))]
calAlim['Ratio (kcal/kg)'] = calAlim['Disponibilité alimentaire (Kcal)'] / calAlim['Disponibilité alimentaire en quantité (kg)']
calAlim = calAlim.groupby('Produit').mean()
calAlim.drop(['Population', 'Code zone', 'Code Produit'], axis = 1, inplace = True)
calAlim = calAlim.sort_values(by = 'Ratio (kcal/kg)', ascending = False)
calAlim.head(20)



/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Aliments pour animaux  \
Produit                                           
Huiles de Foie de Poisso               0.000000   
Huile de Son de Riz                    0.000000   
Huile de Sésame                        0.000000   
Huiles de Poissons                    14.333333   
Huile d'Arachide                       0.000000   
Huile de Germe de Maïs                 0.000000   
Huile d'Olive                          0.000000   
Huil Plantes Oleif Autr                0.000000   
Huile de Palmistes                     0.000000   
Huile Graines de Coton                 0.000000   
Huile de Palme                         0.000000   
Huile de Tournesol                     0.000000   
Huile de Soja                          0.083969   
Huile de Colza&Moutarde               10.937500   
Huile de Coco                          0.000000   
Graisses Animales Crue                10.957746   
Beurre, Ghee                           0.047244   
Palmistes                              0.000000   
Sésame                                 0.000000   
Arachides Decortiquees                 0.007519   

                          Autres utilisations (non alimentaire)  \
Produit                                                           
Huiles de Foie de Poisso                               0.000000   
Huile de Son de Riz                                   16.500000   
Huile de Sésame                                        8.666667   
Huiles de Poissons                                     4.000000   
Huile d'Arachide                                      15.554054   
Huile de Germe de Maïs                                 0.986667   
Huile d'Olive                                          3.759036   
Huil Plantes Oleif Autr                               30.068376   
Huile de Palmistes                                    67.729167   
Huile Graines de Coton                                16.507937   
Huile de Palme                                       279.884615   
Huile de Tournesol                                    26.811475   
Huile de Soja                                        133.282443   
Huile de Colza&Moutarde                              191.640625   
Huile de Coco                                         11.112676   
Graisses Animales Crue                                75.802817   
Beurre, Ghee                                           0.275591   
Palmistes                                              0.000000   
Sésame                                                 0.283582   
Arachides Decortiquees                                 9.511278   

                          Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                                    
Huiles de Foie de Poisso                                       10.000000   
Huile de Son de Riz                                             7.916667   
Huile de Sésame                                                 9.393939   
Huiles de Poissons                                             34.000000   
Huile d'Arachide                                               26.337838   
Huile de Germe de Maïs                                         20.266667   
Huile d'Olive                                                  28.638554   
Huil Plantes Oleif Autr                                        21.786325   
Huile de Palmistes                                             15.333333   
Huile Graines de Coton                                         21.333333   
Huile de Palme                                                 85.230769   
Huile de Tournesol                                             75.098361   
Huile de Soja                                                  79.236641   
Huile de Colza&Moutarde                                        61.718750   
Huile de Coco                                                  20.957746   
Graisses Animales Crue                                         45.443662   
Beurre, Ghee                                                

5 aliments parmi les 20 aliments les plus riches en calories : Huile de coco, Sésame, Huile d'olive, Huile de palme et huile de soja 

## Aliments les plus riches en protéines

In [29]:
protAlim = animVégé.loc[(~animVégé["Disponibilité de protéines en quantité (g/personne/jour)"].isin(["inf", "NaN",0]))&(~animVégé["Disponibilité alimentaire en quantité (kg/personne/an)"].isin(["inf", "NaN",0]))]
protAlim['Ratio (prot/kg)'] = (protAlim['Disponibilité de protéines en quantité (g/personne/jour)'] / 1000*365) / protAlim['Disponibilité alimentaire en quantité (kg/personne/an)']
protAlim = protAlim.groupby('Produit').mean()
protAlim['Protéines (%)'] = protAlim.loc[:,['Ratio (prot/kg)']] * 100
protAlim = protAlim.sort_values(by = 'Protéines (%)', ascending = False)
protAlim.loc[['Avoine'],['Ratio (prot/kg)']]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Ratio (prot/kg)
Produit                 
Avoine          0.087648

Teneur théorique en protéines de l'avoine 10,70g pour 100g soit :

In [30]:
théorieProtAvoine = 10.70 / 100 
print(théorieProtAvoine)

0.107


Cette valeur correspond bien à la fourchette du ratio calculé dans le dataframe 

In [31]:
protAlim.head(20)

Code zone    Population  Code Produit  \
Produit                                                            
Graines Colza/Moutarde     39.000000  1.191467e+07        2558.0   
Soja                      130.887931  5.267748e+07        2555.0   
Arachides Decortiquees    127.592593  4.212246e+07        2556.0   
Pois                      129.137681  4.680899e+07        2547.0   
Légumineuses Autres       127.083871  4.352835e+07        2549.0   
Haricots                  127.172414  4.452752e+07        2546.0   
Plantes Oleiferes, Autre  143.238095  3.212132e+07        2570.0   
Sésame                    130.602041  5.727970e+07        2561.0   
Viande, Autre             128.589744  4.405349e+07        2735.0   
Abats Comestible          126.883041  4.092004e+07        2736.0   
Aliments pour enfants     127.461538  2.945581e+07        2680.0   
Cephalopodes              123.732143  4.059242e+07        2766.0   
Viande de Bovins          126.883041  4.092004e+07        2731.0   
Viande d'Ovins/Caprins    126.541667  4.150147e+07        2732.0   
Viande de Volailles       126.883041  4.092004e+07        2734.0   
Piments                   135.261261  5.602520e+07        2641.0   
Poissons Pelagiques       125.940120  4.075995e+07        2763.0   
Graines de tournesol      130.833333  2.891369e+07        2557.0   
Poissons Marins, Autres   124.525641  3.829247e+07        2764.0   
Poivre                    132.406780  4.830375e+07        2640.0   

                          Aliments pour animaux  \
Produit                                           
Graines Colza/Moutarde               246.333333   
Soja                                 138.439655   
Arachides Decortiquees                 0.006173   
Pois                                  23.891304   
Légumineuses Autres                   42.103226   
Haricots                              16.255172   
Plantes Oleiferes, Autre               9.936508   
Sésame                                 0.000000   
Viande, Autre                          0.358974   
Abats Comestible                       5.900585   
Aliments pour enfants                  0.000000   
Cephalopodes                           0.348214   
Viande de Bovins                       0.052632   
Viande d'Ovins/Caprins                 0.107143   
Viande de Volailles                    0.000000   
Piments                                0.000000   
Poissons Pelagiques                  112.574850   
Graines de tournesol                  13.452381   
Poissons Marins, Autres                8.788462   
Poivre                                 0.000000   

                          Autres utilisations (non alimentaire)  \
Produit                                                           
Graines Colza/Moutarde                                 0.000000   
Soja                                                   5.456897   
Arachides Decortiquees                                 7.808642   
Pois                                                   0.202899   
Légumineuses Autres                                    5.264516   
Haricots                                               0.406897   
Plantes Oleiferes, Autre                               3.492063   
Sésame                                                 0.193878   
Viande, Autre                                          0.096154   
Abats Comestible                                       4.959064   
Aliments pour enfants                                  0.000000   
Cephalopodes                                           0.223214   
Viande de Bovins                                       0.514620   
Viande d'Ovins/Caprins                                 0.375000   
Viande de Volailles                                    7.362573   
Piments                                                0.765766   
Poissons Pelagiques                                    2.251497   
Graines de tournesol                                   0.000000   
Poissons Marins, Autres                                1.076923   


5 aliments parmi les 20 aliments les plus riches en protéines : soja, pois, haricots, sésame et piments

## 6) Disponibilité intérieure mondiale des végétaux (en Kcal)

In [32]:
calAlim = calAlim.loc[:,['Ratio (kcal/kg)']]
protAlim = protAlim.loc[:,['Ratio (prot/kg)']]
ratios = protAlim.join(calAlim, how = 'outer')
dispoVégé = animVégé [(animVégé["Origine"] == "Végétaux")]
dispoVégé = dispoVégé.groupby(['Produit', 'Code Produit'],as_index=True).sum()
dispoVégé = pd.merge(dispoVégé, ratios, left_index = True, right_index = True, how='left')
dispoVégé.drop(['Population', 'Code zone'], axis = 1, inplace = True)
dispoVégé['Disponibilité intérieure mondiale (Kcal)'] = dispoVégé['Disponibilité intérieure']*1000000*dispoVégé['Ratio (kcal/kg)']
dispoVégé['Disponibilité intérieure mondiale de protéines (kg)'] = dispoVégé['Disponibilité intérieure']*1000000* dispoVégé['Ratio (prot/kg)']
dispoVégé

Aliments pour animaux  \
Produit                Code Produit                          
Agrumes, Autres        2614                            0.0   
Alcool, non Comestible 2659                            0.0   
Aliments pour enfants  2680                            0.0   
Ananas                 2618                            0.0   
Arachides Decortiquees 2556                            1.0   
...                                                    ...   
Sésame                 2561                            3.0   
Thé                    2635                            0.0   
Tomates                2601                         1870.0   
Vin                    2655                            0.0   
Épices, Autres         2645                            0.0   

                                     Autres utilisations (non alimentaire)  \
Produit                Code Produit                                          
Agrumes, Autres        2614                                           25.0   
Alcool, non Comestible 2659                                        21768.0   
Aliments pour enfants  2680                                            0.0   
Ananas                 2618                                            3.0   
Arachides Decortiquees 2556                                         1265.0   
...                                                                    ...   
Sésame                 2561                                           63.0   
Thé                    2635                                           26.0   
Tomates                2601                                           77.0   
Vin                    2655                                         1588.0   
Épices, Autres         2645                                          185.0   

                                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                Code Produit                                                   
Agrumes, Autres        2614                                                   126.0   
Alcool, non Comestible 2659                                                     0.0   
Aliments pour enfants  2680                                                   604.0   
Ananas                 2618                                                   640.0   
Arachides Decortiquees 2556                                                  3597.0   
...                                                                             ...   
Sésame                 2561                                                   729.0   
Thé                    2635                                                   119.0   
Tomates                2601                                                  1625.0   
Vin                    2655                                                  1992.0   
Épices, Autres         2645                                                   991.0   

                                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                Code Produit                                                           
Agrumes, Autres        2614                                                     205.58        
Alcool, non Comestible 2659                                                       0.00        
Aliments pour enfants  2680                                                      60.36        
Ananas                 2618                                                     634.04        
Arachides Decortiquees 2556                                                     237.45        
...                                                                                ...        
Sésame                 2561                                                      46.40        
Thé                    2635                                                     123.45        
Tomates                2601                                                    3101.48        
Vin                    2655           

In [33]:
dispoMondiale = dispoVégé['Disponibilité intérieure mondiale (Kcal)'].sum()
print(dispoMondiale)

1.3780136677764186e+16


## 7) Disponibilité intérieure mondiale de produits végétaux / personne

### Besoins journaliers en calories pour un homme et une femme : 

Source Nutripro.Néstlé selon OMS : https://www.nutripro.nestle.fr/dossier/nutrition-generale/vie-quotidienne-et-equilibre-alimentaire/les-apports-nutritionnels-conseilles-anc/apports-nutritionnels-conseilles-adulte#

Âge - Hômme - Femme

20 - 40 ans - 2 700 kcal - 2 200 kcal

41 - 60 ans - 2 500 kcal - 2 000 kcal

Moyenne des besoins journliers en kcal :

In [34]:
moyCalJour = (2700 + 2200 + 2000 + 2500) / 4
print(moyCalJour)

2350.0


Un être humain a besoin en moyenne de 2350 calories journalières 

In [35]:
calPop = (dispoMondiale/365) / moyCalJour
print(calPop)

16065446432.83496


La disponibilité intérieure mondiale pourrait nourrir 15959811049 personnes

In [36]:
pourcentageCal = calPop / popTotale *100
print(pourcentageCal)

229.59408255146266


Soit 228.08% de la population en 2013

### Disponibilité intérieure de protéines  (kg)

In [37]:
dispoProtInt = dispoVégé['Disponibilité intérieure mondiale de protéines (kg)'].sum()
print(dispoProtInt)

352756218695.04663


### Besoins journaliers de protéines d'une personne sédentaire 

Source EurékaSanté : https://eurekasante.vidal.fr/nutrition/corps-aliments/proteines.html?pb=besoins#:~:text=Les%20besoins%20en%20prot%C3%A9ines%20d,fromage%20r%C3%A9partis%20dans%20la%20journ%C3%A9e).

Les besoins d'une personne sédentaire sont d'environ 0,8 g de protéines par kilo de poids et par jour (soit 44 g par jour pour une femme de 55 kilos et 60 g pour un homme de 75 kilos)
                                                                                                       

In [38]:
moyProtJour = (44+60)/2
print(moyProtJour)

52.0


Les besoins d'une personne sédentaire sont d'environ 52 g en moyenne de protéines par jour

In [39]:
protPop = (dispoProtInt/365) / (moyProtJour/1000)
print(protPop)

18585680647.789604


Il serait possible de nourrir 19452982571 personnes en cumulant les protéines végétales disponibles 

In [40]:
pourcentageProt = protPop / popTotale * 100
print(pourcentageProt)

265.6111870132906


Soit 278% de la population totale en 2013

## 8) Disponibilité alimentaire en produits végétaux + nourriture végétale destinée aux animaux + pertes de produits végétaux 


### Disponibilité en Kcal

In [41]:
dispoVégé['Total alimentation / animaux / pertes (Kg)'] = dispoVégé['Disponibilité alimentaire en quantité (kg)'] + dispoVégé['Pertes'] * 1000000 + dispoVégé['Aliments pour animaux']* 1000000
dispoVégé['Total alimentation / animaux / pertes (Kcal)'] = dispoVégé['Total alimentation / animaux / pertes (Kg)']* dispoVégé['Ratio (kcal/kg)']
dispoVégé


Aliments pour animaux  \
Produit                Code Produit                          
Agrumes, Autres        2614                            0.0   
Alcool, non Comestible 2659                            0.0   
Aliments pour enfants  2680                            0.0   
Ananas                 2618                            0.0   
Arachides Decortiquees 2556                            1.0   
...                                                    ...   
Sésame                 2561                            3.0   
Thé                    2635                            0.0   
Tomates                2601                         1870.0   
Vin                    2655                            0.0   
Épices, Autres         2645                            0.0   

                                     Autres utilisations (non alimentaire)  \
Produit                Code Produit                                          
Agrumes, Autres        2614                                           25.0   
Alcool, non Comestible 2659                                        21768.0   
Aliments pour enfants  2680                                            0.0   
Ananas                 2618                                            3.0   
Arachides Decortiquees 2556                                         1265.0   
...                                                                    ...   
Sésame                 2561                                           63.0   
Thé                    2635                                           26.0   
Tomates                2601                                           77.0   
Vin                    2655                                         1588.0   
Épices, Autres         2645                                          185.0   

                                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                Code Produit                                                   
Agrumes, Autres        2614                                                   126.0   
Alcool, non Comestible 2659                                                     0.0   
Aliments pour enfants  2680                                                   604.0   
Ananas                 2618                                                   640.0   
Arachides Decortiquees 2556                                                  3597.0   
...                                                                             ...   
Sésame                 2561                                                   729.0   
Thé                    2635                                                   119.0   
Tomates                2601                                                  1625.0   
Vin                    2655                                                  1992.0   
Épices, Autres         2645                                                   991.0   

                                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                Code Produit                                                           
Agrumes, Autres        2614                                                     205.58        
Alcool, non Comestible 2659                                                       0.00        
Aliments pour enfants  2680                                                      60.36        
Ananas                 2618                                                     634.04        
Arachides Decortiquees 2556                                                     237.45        
...                                                                                ...        
Sésame                 2561                                                      46.40        
Thé                    2635                                                     123.45        
Tomates                2601                                                    3101.48        
Vin                    2655           

In [42]:
dispoAlimTotale = dispoVégé['Total alimentation / animaux / pertes (Kcal)'].sum()
print(dispoAlimTotale)

9504447063649966.0


La somme totale des 3 catégories d'aliments représente 9502405437895988.0 Kcal

In [43]:
calAlimTotale = (dispoAlimTotale/365) / moyCalJour
print(calAlimTotale)

11080672764.383522


La somme des 3 catégories alimentaire pourrait nourrir 11078720102 personnes

In [44]:
pourcentagecalAlim = calAlimTotale / popTotale * 100
print(pourcentagecalAlim)

158.35581712762163


Soit 158.33% de la population totale en 2013

### Disponibilité en protéines

In [45]:
dispoVégé['Total protéines / animaux / pertes (kg)'] = dispoVégé['Total alimentation / animaux / pertes (Kg)']* dispoVégé['Ratio (prot/kg)']
dispoVégé


Aliments pour animaux  \
Produit                Code Produit                          
Agrumes, Autres        2614                            0.0   
Alcool, non Comestible 2659                            0.0   
Aliments pour enfants  2680                            0.0   
Ananas                 2618                            0.0   
Arachides Decortiquees 2556                            1.0   
...                                                    ...   
Sésame                 2561                            3.0   
Thé                    2635                            0.0   
Tomates                2601                         1870.0   
Vin                    2655                            0.0   
Épices, Autres         2645                            0.0   

                                     Autres utilisations (non alimentaire)  \
Produit                Code Produit                                          
Agrumes, Autres        2614                                           25.0   
Alcool, non Comestible 2659                                        21768.0   
Aliments pour enfants  2680                                            0.0   
Ananas                 2618                                            3.0   
Arachides Decortiquees 2556                                         1265.0   
...                                                                    ...   
Sésame                 2561                                           63.0   
Thé                    2635                                           26.0   
Tomates                2601                                           77.0   
Vin                    2655                                         1588.0   
Épices, Autres         2645                                          185.0   

                                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                Code Produit                                                   
Agrumes, Autres        2614                                                   126.0   
Alcool, non Comestible 2659                                                     0.0   
Aliments pour enfants  2680                                                   604.0   
Ananas                 2618                                                   640.0   
Arachides Decortiquees 2556                                                  3597.0   
...                                                                             ...   
Sésame                 2561                                                   729.0   
Thé                    2635                                                   119.0   
Tomates                2601                                                  1625.0   
Vin                    2655                                                  1992.0   
Épices, Autres         2645                                                   991.0   

                                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                Code Produit                                                           
Agrumes, Autres        2614                                                     205.58        
Alcool, non Comestible 2659                                                       0.00        
Aliments pour enfants  2680                                                      60.36        
Ananas                 2618                                                     634.04        
Arachides Decortiquees 2556                                                     237.45        
...                                                                                ...        
Sésame                 2561                                                      46.40        
Thé                    2635                                                     123.45        
Tomates                2601                                                    3101.48        
Vin                    2655           

In [46]:
dispoProtTotale = dispoVégé['Total protéines / animaux / pertes (kg)'].sum()
print(dispoProtTotale)

215650114210.3063


La somme totale des 3 catégories d'aliments représente 217079540267.1754 kg de protéines 

In [47]:
protPop3 = (dispoProtTotale/365) / (moyProtJour/1000)
print(protPop3)

11361965975.25323


La somme des 3 catégories alimentaire pourrait nourrir 11437278201 personnes

In [48]:
protPopTotale = protPop3 / popTotale * 100
print(protPopTotale)

162.37582721246986


Soit 163.45% de la population totale en 2013

## 9) Disponibilité alimentaire mondiale 

In [49]:
dispoAlim = animVégé.groupby('Produit').sum()
dispoAlim.drop(['Population', 'Code zone', 'Code Produit'], axis = 1, inplace = True)
dispoAlim


Aliments pour animaux  \
Produit                                         
Abats Comestible                       1009.0   
Agrumes, Autres                           0.0   
Alcool, non Comestible                    0.0   
Aliments pour enfants                     0.0   
Ananas                                    0.0   
...                                       ...   
Viande de Suides                          0.0   
Viande de Volailles                       0.0   
Viande, Autre                            57.0   
Vin                                       0.0   
Épices, Autres                            0.0   

                        Autres utilisations (non alimentaire)  \
Produit                                                         
Abats Comestible                                        848.0   
Agrumes, Autres                                          25.0   
Alcool, non Comestible                                21768.0   
Aliments pour enfants                                     0.0   
Ananas                                                    3.0   
...                                                       ...   
Viande de Suides                                        283.0   
Viande de Volailles                                    1259.0   
Viande, Autre                                            15.0   
Vin                                                    1588.0   
Épices, Autres                                          185.0   

                        Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                                  
Abats Comestible                                                1375.0   
Agrumes, Autres                                                  126.0   
Alcool, non Comestible                                             0.0   
Aliments pour enfants                                            604.0   
Ananas                                                           640.0   
...                                                                ...   
Viande de Suides                                               14171.0   
Viande de Volailles                                            12565.0   
Viande, Autre                                                   1055.0   
Vin                                                             1992.0   
Épices, Autres                                                   991.0   

                        Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                                          
Abats Comestible                                                   440.37        
Agrumes, Autres                                                    205.58        
Alcool, non Comestible                                               0.00        
Aliments pour enfants                                               60.36        
Ananas                                                             634.04        
...                                                                   ...        
Viande de Suides                                                  2300.32        
Viande de Volailles                                               3454.95        
Viande, Autre                                                      309.59        
Vin                                                               1043.20        
Épices, Autres                                                     104.58        

                        Disponibilité de matière grasse en quantité (g/personne/jour)  \
Produit                                                                                 
Abats Comestible                                                    40.85               
Agrumes, Autres                                                      0.77               
Alcool, non Comestible                                               0.00               
Aliments pour enfants                                            

### Disponibilité alimentaire mondiale en Kcal

In [50]:
dispoAlimMonde = dispoAlim['Disponibilité alimentaire (Kcal)'].sum()
dispoAlimMonde

7364437353675000.0

La disponibilité alimenaitre mondiale est de 7364437353675000.0 Kcal

In [51]:
dispoAlimMondePop = (dispoAlimMonde/365) / moyCalJour
print(dispoAlimMondePop)

8585761997.87234


La disponibilité alimentaire mondiale pourrait nourrir 8585761997 personnes

In [52]:
dispoAlimMondePourc = dispoAlimMondePop / popTotale *100
print(dispoAlimMondePourc)

122.700614461472


Soit 122.70% de la population en 2013

### Disponibilité alimentaire de protéines (kg)

In [53]:
dispoProtMonde = dispoAlim['Disponibilité de protéines en quantité (Kg)'].sum()
dispoProtMonde

207249144517.35

La disponibilité alimentaire de protéines est équivalente à 207249144517.35 kg

In [54]:
dispoProtMondePop = (dispoProtMonde/365) / (moyProtJour/1000)
print(dispoProtMondePop)

10919343757.5


La disponibilité alimentaire de protéines pourrait nourrir 10919343757 personnes 

In [55]:
dispoProtMondePourc = dispoProtMondePop / popTotale * 100
print(dispoProtMondePourc)

156.05023629740847


Soit 156.05% de la population totale en 2013


## 10) Proportion de la population mondiale considérée comme étant en sous-nutrition

In [56]:
alim2013 = alim2013.dropna(subset=['Valeur']) 
alim2013['Valeur'] = alim2013['Valeur'].replace(['<0.1'], 0.05)
alim2013["Valeur"] = pd.to_numeric(alim2013["Valeur"])
alim2013

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Code zone                                    Zone  Population  \
0            2                             Afghanistan    30552000   
1          202                          Afrique du Sud    52776000   
2            3                                 Albanie     3173000   
3            4                                 Algérie    39208000   
5            7                                  Angola    21472000   
..         ...                                     ...         ...   
166        236  Venezuela (République bolivarienne du)    30405000   
167        237                                Viet Nam    91680000   
168        249                                   Yémen    24407000   
169        251                                  Zambie    14539000   
170        181                                Zimbabwe    14150000   

                                               Produit  Code Produit  \
0    Nombre de personnes sous-alimentées (millions)...      210011.0   
1    Nombre de personnes sous-alimentées (millions)...      210011.0   
2    Nombre de personnes sous-alimentées (millions)...      210011.0   
3    Nombre de personnes sous-alimentées (millions)...      210011.0   
5    Nombre de personnes sous-alimentées (millions)...      210011.0   
..                                                 ...           ...   
166  Nombre de personnes sous-alimentées (millions)...      210011.0   
167  Nombre de personnes sous-alimentées (millions)...      210011.0   
168  Nombre de personnes sous-alimentées (millions)...      210011.0   
169  Nombre de personnes sous-alimentées (millions)...      210011.0   
170  Nombre de personnes sous-alimentées (millions)...      210011.0   

         Année     Unité  Valeur Description du Symbole Symbole  
0    2012-2014  millions     7.9         Estimation FAO       F  
1    2012-2014  millions     2.6         Estimation FAO       F  
2    2012-2014  millions     0.2         Estimation FAO       F  
3    2012-2014  millions     1.7         Estimation FAO       F  
5    2012-2014  millions     8.1         Estimation FAO       F  
..         ...       ...     ...                    ...     ...  
166  2012-2014  millions     1.9         Estimation FAO       F  
167  2012-2014  millions    10.4         Estimation FAO       F  
168  2012-2014  millions     7.2         Estimation FAO       F  
169  2012-2014  millions     7.0         Estimation FAO       F  
170  2012-2014  millions     6.6         Estimation FAO       F  

[117 rows x 10 columns]

In [57]:
popSousAlim = alim2013['Valeur'].sum()
print(popSousAlim)

744.9


La proportion de la population mondiale considérée comme étant en sous alimentation s'élevait à 744.9 millions de personnes en 2013

In [58]:
proportionSousAlim = (popSousAlim * 1000000) / popTotale *100
print(proportionSousAlim)

10.64549515057609


Soit 10.64% de la population mondiale 

### Liste des produits (ainsi que leur code) considérés comme des céréales selon la FAO 

In [59]:
listeCéré = céré.groupby(['Produit', 'Code Produit'],as_index=True).sum()
listeCéré = listeCéré.loc[:,[]]
listeCéré['Type'] = 'Céréale'
listeCéré

Type
Produit          Code Produit         
Avoine           2516          Céréale
Blé              2511          Céréale
Céréales, Autres 2520          Céréale
Maïs             2514          Céréale
Millet           2517          Céréale
Orge             2513          Céréale
Riz (Eq Blanchi) 2805          Céréale
Seigle           2515          Céréale
Sorgho           2518          Céréale

In [60]:
infoCéré = pd.merge(listeCéré, dispoVégé, left_index = True, right_index = True, how='left')
infoCéré

Type  Aliments pour animaux  \
Produit          Code Produit                                   
Avoine           2516          Céréale                16251.0   
Blé              2511          Céréale               129668.0   
Céréales, Autres 2520          Céréale                19036.0   
Maïs             2514          Céréale               546116.0   
Millet           2517          Céréale                 3306.0   
Orge             2513          Céréale                92658.0   
Riz (Eq Blanchi) 2805          Céréale                33594.0   
Seigle           2515          Céréale                 8099.0   
Sorgho           2518          Céréale                24808.0   

                               Autres utilisations (non alimentaire)  \
Produit          Code Produit                                          
Avoine           2516                                          206.0   
Blé              2511                                        22423.0   
Céréales, Autres 2520                                         1388.0   
Maïs             2514                                       189387.0   
Millet           2517                                          196.0   
Orge             2513                                          654.0   
Riz (Eq Blanchi) 2805                                        18465.0   
Seigle           2515                                           20.0   
Sorgho           2518                                         2049.0   

                               Disponibilité alimentaire (Kcal/personne/jour)  \
Produit          Code Produit                                                   
Avoine           2516                                                   854.0   
Blé              2511                                                 94846.0   
Céréales, Autres 2520                                                  1446.0   
Maïs             2514                                                 30799.0   
Millet           2517                                                  3964.0   
Orge             2513                                                  1804.0   
Riz (Eq Blanchi) 2805                                                 51771.0   
Seigle           2515                                                  1967.0   
Sorgho           2518                                                  4952.0   

                               Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit          Code Produit                                                           
Avoine           2516                                                     147.04        
Blé              2511                                                   12178.78        
Céréales, Autres 2520                                                     188.57        
Maïs             2514                                                    3677.13        
Millet           2517                                                     512.88        
Orge             2513                                                     262.43        
Riz (Eq Blanchi) 2805                                                    5257.90        
Seigle           2515                                                     263.36        
Sorgho           2518                                                     613.99        

                               Disponibilité de matière grasse en quantité (g/personne/jour)  \
Produit          Code Produit                                                                  
Avoine           2516                                                      14.91               
Blé              2511                                                     536.92               
Céréales, Autres 2520                                                       5.35               
Maïs             2514                                                     271.19               
Millet           2517                                                      37

## 11) Proportion de nourriture céréalière (en termes de poids) destinée à l'alimentation animale 

In [61]:
(infoCéré['Aliments pour animaux'].sum()*1000000) / (infoCéré['Disponibilité alimentaire en quantité (kg)'].sum()+(infoCéré['Aliments pour animaux'].sum()*1000000))*100

45.91400584899829

45,91% de la quantité de nourriture est destinée aux animaux 

### Les 15 produits les plus exportés par les pays considérés comme en sous-alimentation 

In [62]:
infoSousAlim = pd.merge(animVégé, alim2013, on='Code zone', how='left')
infoSousAlim = infoSousAlim.dropna(subset=['Année']) 
infoSousAlim = infoSousAlim.groupby('Produit_x').sum()
infoSousAlim = infoSousAlim.sort_values(by = 'Exportations - Quantité', ascending = False)
infoSousAlim = infoSousAlim.head(15)
infoSousAlim

Code zone  Population_x  Code Produit_x  \
Produit_x                                                      
Huile de Palme           14201    5379443000          293778   
Maïs                     14634    5388396000          294138   
Manioc                   13721    5193730000          281052   
Riz (Eq Blanchi)         14634    5388396000          328185   
Sucre Eq Brut            14634    5388396000          297414   
Blé                      14634    5388396000          293787   
Légumes, Autres          14634    5388396000          304785   
Bananes                  13921    5125295000          292880   
Fruits, Autres           14634    5388396000          307125   
Lait - Excl Beurre       14634    5388396000          333216   
Soja                     13781    5330319000          278495   
Poissons Pelagiques      14632    5357844000          320508   
Tomates                  14397    5296716000          301716   
Pommes                   14634    5388396000          306189   
Oranges, Mandarines      14606    5335137000          302876   

                     Aliments pour animaux  \
Produit_x                                    
Huile de Palme                         0.0   
Maïs                              263458.0   
Manioc                             75747.0   
Riz (Eq Blanchi)                   33034.0   
Sucre Eq Brut                         23.0   
Blé                                48295.0   
Légumes, Autres                    37626.0   
Bananes                              854.0   
Fruits, Autres                        43.0   
Lait - Excl Beurre                 40366.0   
Soja                               12115.0   
Poissons Pelagiques                13130.0   
Tomates                                0.0   
Pommes                               238.0   
Oranges, Mandarines                   11.0   

                     Autres utilisations (non alimentaire)  \
Produit_x                                                    
Huile de Palme                                     24795.0   
Maïs                                               46100.0   
Manioc                                             34116.0   
Riz (Eq Blanchi)                                   17972.0   
Sucre Eq Brut                                       6154.0   
Blé                                                10302.0   
Légumes, Autres                                       83.0   
Bananes                                              128.0   
Fruits, Autres                                        85.0   
Lait - Excl Beurre                                  1644.0   
Soja                                                 638.0   
Poissons Pelagiques                                  266.0   
Tomates                                               49.0   
Pommes                                                20.0   
Oranges, Mandarines                                   31.0   

                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit_x                                                             
Huile de Palme                                               7062.0   
Maïs                                                        26235.0   
Manioc                                                       8819.0   
Riz (Eq Blanchi)                                            45570.0   
Sucre Eq Brut                                               26676.0   
Blé                                                         55687.0   
Légumes, Autres                                              4347.0   
Bananes                                                      3033.0   
Fruits, Autres                                               3135.0   
Lait - Excl Beurre                                          14187.0   
Soja                                                          636.0   
Poissons Pelagiques                                          1937.0   
Tomates                                                       871.0   
Pommes                       

### Liste des 200 plus grandes importations des 15 produits les plus exportés par les pays considérés comme en sous-alimentation

In [63]:
infoSousAlim.index.names = ['Produit']
infoSousAlim = infoSousAlim.reset_index()
infoSousAlim = infoSousAlim.loc[:,['Produit']]
infoSousAlim = pd.merge(animVégé, infoSousAlim, on='Produit')
infoSousAlim = infoSousAlim.sort_values(by = 'Importations - Quantité', ascending = False)
infoSousAlim = infoSousAlim.head(200)
infoSousAlim


Code zone      Zone  Population             Produit  Code Produit  \
2406        351     Chine  1416667000                Soja          2555   
2072        351     Chine  1416667000              Manioc          2532   
1096        110     Japon   127144000                Maïs          2514   
209          59    Égypte    82056000                 Blé          2511   
707         351     Chine  1416667000  Lait - Excl Beurre          2848   
...         ...       ...         ...                 ...           ...   
290         173   Pologne    38217000                 Blé          2511   
1047         33    Canada    35182000                Maïs          2514   
698          21    Brésil   200362000  Lait - Excl Beurre          2848   
176          11  Autriche     8495000                 Blé          2511   
197          40     Chili    17620000                 Blé          2511   

       Origine  Aliments pour animaux  Autres utilisations (non alimentaire)  \
2406  Végétaux                 9530.0                                    1.0   
2072  Végétaux                22873.0                                 9257.0   
1096  Végétaux                10964.0                                  288.0   
209   Végétaux                 4860.0                                    0.0   
707    Animaux                 1632.0                                   42.0   
...        ...                    ...                                    ...   
290   Végétaux                 2600.0                                  650.0   
1047  Végétaux                10723.0                                  249.0   
698    Animaux                 1898.0                                  100.0   
176   Végétaux                  467.0                                   58.0   
197   Végétaux                  145.0                                    2.0   

      Disponibilité alimentaire (Kcal/personne/jour)  \
2406                                            36.0   
2072                                             6.0   
1096                                            61.0   
209                                           1175.0   
707                                             59.0   
...                                              ...   
290                                            877.0   
1047                                           113.0   
698                                            252.0   
176                                            645.0   
197                                            830.0   

      Disponibilité alimentaire en quantité (kg/personne/an)  ...  \
2406                                               3.87       ...   
2072                                               1.88       ...   
1096                                               9.21       ...   
209                                              146.83       ...   
707                                               33.18       ...   
...                                                 ...       ...   
290                                              108.83       ...   
1047                                              18.95       ...   
698                                              149.28       ...   
176                                               81.10       ...   
197                                              104.74       ...   

      Importations - Quantité  Nourriture  Pertes  Production  Semences  \
2406                  65564.0      5489.0   610.0     11951.0     713.0   
2072                  30466.0      2657.0   138.0      4600.0       0.0   
1096                  14403.0      1171.0     3.0         0.0       0.0   
209                   10331.0     12048.0  2224.0      9460.0     217.0   
707                    9780.0     47009.0  1433.0     40570.0       0.0   
...                       ...         ...     ...         ...       ...   
290                    1037.0      4159.0   500.0      9485.0     600.0   
1047                   1035.0       667.0 

In [64]:
infoSousAlim = infoSousAlim.groupby('Produit').sum()
infoSousAlim.drop(['Population', 'Code zone', 'Code Produit'], axis = 1, inplace = True)
infoSousAlim['Ratio Autre util/Dispo intérieure'] = infoSousAlim['Autres utilisations (non alimentaire)'] / infoSousAlim['Disponibilité intérieure']
infoSousAlim['Ratio Anim/Total'] = infoSousAlim['Aliments pour animaux'] / infoSousAlim['Nourriture']
infoSousAlim

Aliments pour animaux  \
Produit                                      
Bananes                                0.0   
Blé                                98715.0   
Fruits, Autres                         0.0   
Huile de Palme                         0.0   
Lait - Excl Beurre                 29133.0   
Légumes, Autres                    39562.0   
Manioc                             25153.0   
Maïs                              402887.0   
Oranges, Mandarines                    0.0   
Poissons Pelagiques                13097.0   
Pommes                                 0.0   
Riz (Eq Blanchi)                   12709.0   
Soja                               13710.0   
Sucre Eq Brut                          0.0   
Tomates                                0.0   

                     Autres utilisations (non alimentaire)  \
Produit                                                      
Bananes                                                0.0   
Blé                                                15125.0   
Fruits, Autres                                        12.0   
Huile de Palme                                     18726.0   
Lait - Excl Beurre                                 12479.0   
Légumes, Autres                                       19.0   
Manioc                                             20355.0   
Maïs                                              182118.0   
Oranges, Mandarines                                    1.0   
Poissons Pelagiques                                   40.0   
Pommes                                                 0.0   
Riz (Eq Blanchi)                                    2817.0   
Soja                                                 525.0   
Sucre Eq Brut                                       3009.0   
Tomates                                                0.0   

                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                               
Bananes                                                        89.0   
Blé                                                         31770.0   
Fruits, Autres                                                236.0   
Huile de Palme                                                756.0   
Lait - Excl Beurre                                           6225.0   
Légumes, Autres                                               935.0   
Manioc                                                        178.0   
Maïs                                                         4652.0   
Oranges, Mandarines                                           175.0   
Poissons Pelagiques                                           115.0   
Pommes                                                        105.0   
Riz (Eq Blanchi)                                             4363.0   
Soja                                                          239.0   
Sucre Eq Brut                                                3886.0   
Tomates                                                        65.0   

                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                                       
Bananes                                                          53.45        
Blé                                                            4082.84        
Fruits, Autres                                                  195.58        
Huile de Palme                                                   32.09        
Lait - Excl Beurre                                             4494.08        
Légumes, Autres                                                1242.77        
Manioc                                                           61.96        
Maïs                                                            582.94        
Oranges, Mandarines                                             275.78        
Poissons Pelagiques                                              36.16        
Pommes                     

## 12) Les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios

In [65]:
infoSousAlim = infoSousAlim.sort_values(by = 'Ratio Autre util/Dispo intérieure', ascending = False)
infoSousAlim

Aliments pour animaux  \
Produit                                      
Huile de Palme                         0.0   
Manioc                             25153.0   
Maïs                              402887.0   
Sucre Eq Brut                          0.0   
Lait - Excl Beurre                 29133.0   
Blé                                98715.0   
Riz (Eq Blanchi)                   12709.0   
Soja                               13710.0   
Poissons Pelagiques                13097.0   
Fruits, Autres                         0.0   
Oranges, Mandarines                    0.0   
Légumes, Autres                    39562.0   
Bananes                                0.0   
Pommes                                 0.0   
Tomates                                0.0   

                     Autres utilisations (non alimentaire)  \
Produit                                                      
Huile de Palme                                     18726.0   
Manioc                                             20355.0   
Maïs                                              182118.0   
Sucre Eq Brut                                       3009.0   
Lait - Excl Beurre                                 12479.0   
Blé                                                15125.0   
Riz (Eq Blanchi)                                    2817.0   
Soja                                                 525.0   
Poissons Pelagiques                                   40.0   
Fruits, Autres                                        12.0   
Oranges, Mandarines                                    1.0   
Légumes, Autres                                       19.0   
Bananes                                                0.0   
Pommes                                                 0.0   
Tomates                                                0.0   

                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                               
Huile de Palme                                                756.0   
Manioc                                                        178.0   
Maïs                                                         4652.0   
Sucre Eq Brut                                                3886.0   
Lait - Excl Beurre                                           6225.0   
Blé                                                         31770.0   
Riz (Eq Blanchi)                                             4363.0   
Soja                                                          239.0   
Poissons Pelagiques                                           115.0   
Fruits, Autres                                                236.0   
Oranges, Mandarines                                           175.0   
Légumes, Autres                                               935.0   
Bananes                                                        89.0   
Pommes                                                        105.0   
Tomates                                                        65.0   

                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                                       
Huile de Palme                                                   32.09        
Manioc                                                           61.96        
Maïs                                                            582.94        
Sucre Eq Brut                                                   398.11        
Lait - Excl Beurre                                             4494.08        
Blé                                                            4082.84        
Riz (Eq Blanchi)                                                439.39        
Soja                                                             26.30        
Poissons Pelagiques                                              36.16        
Fruits, Autres                                                  195.58        
Oranges, Mandarines        

Huile de Palme, Manioc et Maïs sont les trois produits dont le ratio autre utilisation sur disponibilité intérieure est le plus élèvé 

In [66]:
infoSousAlim = infoSousAlim.sort_values(by = 'Ratio Anim/Total', ascending = False)
infoSousAlim

Aliments pour animaux  \
Produit                                      
Maïs                              402887.0   
Poissons Pelagiques                13097.0   
Soja                               13710.0   
Manioc                             25153.0   
Blé                                98715.0   
Riz (Eq Blanchi)                   12709.0   
Lait - Excl Beurre                 29133.0   
Légumes, Autres                    39562.0   
Huile de Palme                         0.0   
Sucre Eq Brut                          0.0   
Fruits, Autres                         0.0   
Oranges, Mandarines                    0.0   
Bananes                                0.0   
Pommes                                 0.0   
Tomates                                0.0   

                     Autres utilisations (non alimentaire)  \
Produit                                                      
Maïs                                              182118.0   
Poissons Pelagiques                                   40.0   
Soja                                                 525.0   
Manioc                                             20355.0   
Blé                                                15125.0   
Riz (Eq Blanchi)                                    2817.0   
Lait - Excl Beurre                                 12479.0   
Légumes, Autres                                       19.0   
Huile de Palme                                     18726.0   
Sucre Eq Brut                                       3009.0   
Fruits, Autres                                        12.0   
Oranges, Mandarines                                    1.0   
Bananes                                                0.0   
Pommes                                                 0.0   
Tomates                                                0.0   

                     Disponibilité alimentaire (Kcal/personne/jour)  \
Produit                                                               
Maïs                                                         4652.0   
Poissons Pelagiques                                           115.0   
Soja                                                          239.0   
Manioc                                                        178.0   
Blé                                                         31770.0   
Riz (Eq Blanchi)                                             4363.0   
Lait - Excl Beurre                                           6225.0   
Légumes, Autres                                               935.0   
Huile de Palme                                                756.0   
Sucre Eq Brut                                                3886.0   
Fruits, Autres                                                236.0   
Oranges, Mandarines                                           175.0   
Bananes                                                        89.0   
Pommes                                                        105.0   
Tomates                                                        65.0   

                     Disponibilité alimentaire en quantité (kg/personne/an)  \
Produit                                                                       
Maïs                                                            582.94        
Poissons Pelagiques                                              36.16        
Soja                                                             26.30        
Manioc                                                           61.96        
Blé                                                            4082.84        
Riz (Eq Blanchi)                                                439.39        
Lait - Excl Beurre                                             4494.08        
Légumes, Autres                                                1242.77        
Huile de Palme                                                   32.09        
Sucre Eq Brut                                                   398.11        
Fruits, Autres             

Maïs, Poissons Pelagique et Soja sont les trois produits dont le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine) est le plus élèvé 

## 13) Tonnes de céréales pouvant être libérées si les USA diminuaient leur production de produits animaux de 10% 

In [67]:
céréUSA = pd.merge(animVégé, listeCéré, on='Produit')
céréUSA = céréUSA [ (céréUSA["Code zone"] == 231)]
céréUSA


Code zone                   Zone  Population           Produit  \
51          231  États-Unis d'Amérique   320051000               Blé   
221         231  États-Unis d'Amérique   320051000  Céréales, Autres   
391         231  États-Unis d'Amérique   320051000              Maïs   
557         231  États-Unis d'Amérique   320051000            Millet   
715         231  États-Unis d'Amérique   320051000              Orge   
885         231  États-Unis d'Amérique   320051000  Riz (Eq Blanchi)   
1054        231  États-Unis d'Amérique   320051000            Avoine   
1214        231  États-Unis d'Amérique   320051000            Seigle   
1364        231  États-Unis d'Amérique   320051000            Sorgho   

      Code Produit   Origine  Aliments pour animaux  \
51            2511  Végétaux                 6196.0   
221           2520  Végétaux                   77.0   
391           2514  Végétaux               128024.0   
557           2517  Végétaux                  394.0   
715           2513  Végétaux                 1440.0   
885           2805  Végétaux                    0.0   
1054          2516  Végétaux                 1430.0   
1214          2515  Végétaux                  184.0   
1364          2518  Végétaux                 2351.0   

      Autres utilisations (non alimentaire)  \
51                                     16.0   
221                                     0.0   
391                                137023.0   
557                                     0.0   
715                                     0.0   
885                                   142.0   
1054                                    0.0   
1214                                    0.0   
1364                                    0.0   

      Disponibilité alimentaire (Kcal/personne/jour)  \
51                                             599.0   
221                                              5.0   
391                                             92.0   
557                                              0.0   
715                                              5.0   
885                                             72.0   
1054                                            19.0   
1214                                             2.0   
1364                                             7.0   

      Disponibilité alimentaire en quantité (kg/personne/an)  ...  Nourriture  \
51                                                80.43       ...     25742.0   
221                                                0.62       ...       200.0   
391                                               12.24       ...      3917.0   
557                                                0.00       ...         0.0   
715                                                0.50       ...       160.0   
885                                                6.88       ...      2203.0   
1054                                               3.95       ...      1265.0   
1214                                               0.27       ...        87.0   
1364                                               0.74       ...       236.0   

      Pertes  Production  Semences  Traitement  Variation de stock  \
51       0.0     57967.0    2096.0         0.0              5284.0   
221      0.0        81.0       3.0         0.0                 0.0   
391      0.0    353699.0     582.0     23230.0            -39863.0   
557     22.0       418.0       0.0         0.0                 0.0   
715      0.0      4683.0     107.0      3161.0                16.0   
885    200.0      5745.0     109.0       464.0               -27.0   
1054     0.0      1016.0     103.0         0.0                32.0   
1214     0.0       195.0      76.0         0.0               -76.0   
1364     0.0      9882.0      22.0      1753.0             -3220.0   

      Disponibilité alimentaire (Kcal)  \
51                        6.997435e+13   
221                       5.840931e+11   
391                       1.074731e+13   
557                   

In [68]:
céréUSA['Aliments pour animaux'].sum()*0.1


14009.6

14009.6 milliers de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10%

## 14) Proportion de manioc exportée et proportion de personnes en sous-nutrition en Thaïland 

In [69]:
thailande = animVégé [ animVégé["Code zone"] == 216]
thailande[thailande['Produit'] == 'Manioc'].loc[:,'Exportations - Quantité'].sum()


25214.0

La Thaïlande exporte 25214.0 milliers de tonnes de Manioc par an 

In [70]:
thailande[thailande['Produit'] == 'Manioc'].loc[:,'Production'].sum() 

30228.0

In [71]:
thailande[thailande['Produit'] == 'Manioc'].loc[:,'Exportations - Quantité'].sum() / thailande[thailande['Produit'] == 'Manioc'].loc[:,'Production'].sum() * 100


83.41272991928014

La Thaïlande exporte 83.41% du Manioc qu'elle produit par an 

In [72]:
thailande = alim2013 [ alim2013["Code zone"] == 216]
thailande

Code zone       Zone  Population  \
156        216  Thaïlande    67011000   

                                               Produit  Code Produit  \
156  Nombre de personnes sous-alimentées (millions)...      210011.0   

         Année     Unité  Valeur Description du Symbole Symbole  
156  2012-2014  millions     5.6         Estimation FAO       F

La Thaïlande compte 5,6 millions de personnes sous-alimentées 

In [73]:
thailande.loc[:,'Valeur'].sum() * 1000000 / thailande.loc[:,'Population'].sum() * 100


8.356836937219263

Soit 8,36% de sa population 